name: Release

on:
  release:
    branches: main
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Which tag to update to"
        default: "v1"
        required: true

jobs:
  re-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "main"
      - name: update tag
        run: |
          git config user.name 'github-actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git tag --delete ${{ inputs.tag }} || true
          git push --delete origin ${{ inputs.tag }} || true
          git tag -a ${{ inputs.tag }} -m '🔖 Re-tag ${{ inputs.tag }}'
          git push origin ${{ inputs.tag }}
